##
## Build with Travis.CI
##
sudo: required

language: generic

services:
  - docker

script:
- |
  baseDir="$(pwd)" &&\
  echo "Base directors is '$baseDir'." &&\
  inputDir="${baseDir}/book" &&\
  mv "$baseDir/README.md" "$inputDir" &&\
  outputDir="${baseDir}/output" &&\
  echo "Input directory is '$inputDir' and output directory is '$outputDir'." &&\
  mkdir -p "${outputDir}" &&\
  docker run -v "${inputDir}/":/input/ \
             -v "${outputDir}/":/output/ \
             -e TRAVIS_COMMIT=$TRAVIS_COMMIT \
             -e TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
             -t -i thomasweise/docker-bookbuilder book.md aitoa &&\
  cd "${outputDir}"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
  target-branch: gh-pages
  local-dir: output
  
# trigger the build of aitoa-slides after success
after_deploy:
  - ../trigger-travis.sh thomasWeise aitoa-slides $TRAVIS_ACCESS_TOKEN
